[package]
name = "db_ip"
authors = ["Finn Bear"]
version = "0.1.0"
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/finnbear/db_ip/"
description = "An (unofficial) Rust library for querying db-ip.com data"

[features]
default = ["ipv4", "ipv6"]
ipv4 = []
ipv6 = []

[dependencies]
csv = "1.1"
locale-codes = "0.3"
serde = {version = "1.0", features=["derive"], optional=true}
doc-comment = "0.3"

[dev-dependencies]
bincode = "1.3.3"
serde_json = "1.0"